=== hamzaanis10/xml-dtd/data.dtd
<!ELEMENT student (name, age, class, fees*, paid+, paid_to?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT fees (#PCDATA)>
<!ELEMENT paid (#PCDATA)>
<!ELEMENT paid_to (#PCDATA)>
<!ATTLIST name first_name CDATA #IMPLIED>
<!ENTITY nbsp "#hamza10">
<!ENTITY writer-name "Hamza Anis">

=== hamzaanis10/xml-dtd/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE student SYSTEM "data.dtd" [

]>

<student>
    <name>&writer-name;</name>
    <age>&nbsp;</age>
    <class></class>
    <fees>10 &quot; 7</fees>
    <fees></fees>
    <fees></fees>
    <fees></fees>
    <paid></paid>
    <paid_to></paid_to>
</student>
